version: '3'
services:
  mongodb:
    container_name: mongodb
    image: mongo:3.6
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
#    volumes:
#      - ./data/db:/data/db
    ports:
      - 27017:27017

#  app:
#    restart: always
#    build: ./blackkari
#    working_dir: /blackkari
#    volumes:
#      - ./app:/app
#    expose:
#      - "8080"
#    command: npm run dev
#    depends_on:
#      - mongodb